Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/bionic64" 
  
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = 1
    end
  
    config.vm.network "forwarded_port", guest: 80, host: 8080
  
    config.vm.synced_folder "./web", "/var/www/html"
  
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y apache2
      sudo chown -R www-data:www-data /var/www/html
      echo "<h1>Hola Mundo</h1>" > /var/www/html/index.html
      sudo systemctl restart apache2
    SHELL
  end
  